### PR TITLE
Update plugin android with partial results recognition and stop listening

### PR DESCRIPTION
**Pull request by simone-compagnone**
add STOP_LISTENING for android

### CODE REVIEW

**Comment by bandojulio** [comment]
Great feature! I will try it!

**Comment by simone-compagnone** [comment]
Ok perfect! Give me a feedback if you test it.
If the commit work, please merged.
Thanks

**Comment by simone-compagnone** [comment]
Hello,
I have implemented the partial results recognition, the same feature enable in iOS platform.
The developer can set "showPartial" and receive from plugin the partial results, so the frontend can receive partial result and update the view. In this use case, the user can see the words on the view during the dictate mode. This is really a very interesting and useful use case to implemented.
With this commit the plugin can work in the same mode in iOS and Android :)
Please check it and try it! Please give me a feedback.
If you want merge I'm very happy :1st_place_medal:

**Comment by NBAMj** [comment]
Sounds very nice, just about what I was looking for.
Will give it a try 👍

**Comment by NBAMj** [comment]
`showPartial` is indeed returning values to javascript, similar to iOS, but it stops recognizing once you stop saying words, without calling `stopListening()`
In iOS, it continuously listens till `stopListening()` is called.

Have you faced the same issue?

**Comment by simone-compagnone** [comment]
Yes I know but in my opinion is not an issue and this is managed by SO.
The OS in Android **automatically** stop the listening (this is not the same for iOS) when you stop to speech and I can't change this behavior.
So, in Android, if you want to stop the listening you can chose to call stopListening during the speech **OR** wait stop saying words.

**Comment by NBAMj** [comment]
You are right, but is there a way to enable continuous listening in Android.
Something [like](https://stackoverflow.com/questions/14940657/android-speech-recognition-as-a-service-on-android-4-1-4-2) maybe

**Comment by NBAMj** [comment]
One more thing, is there a way to receive an event when listening has stopped in Android?
For example, showing a spinner loader when listening and removing it when listening has stopped.

**Comment by simone-compagnone** [comment]
I wanted to implement it but I can't because my solution have many problem of regression.
For your use case you can start a timeout (for example 2 or 3 sec) after the last word arrived and force the stop listening.

**Comment by simone-compagnone** [comment]
@pbakondy please test the feature and, if you want, merge it.

**Comment by pbakondy** [comment]
thanks

**Pull request merged**
